sudo: false
dist: xenial
language: java
jdk:
  - oraclejdk8

git:
  submodules: false
  depth: false
  quiet: true

branches:
  only:
  - master

before_install:
  - export TZ='Asia/Shanghai'

install: true

script:
  - cd algorithms/java-solution && ./gradlew check
